### ISSUE TITLE
Wonky File Permissions

### ISSUE THREAD

**Issue by brannondorsey** [brannondorsey/kibio#1]
@bakercp I'm implementing a "new project" feature (cmd-n) that copies a template project folder from `data/templates/TemplateProject` to `~/Documents/Kibio/PROJECT_NAME`, but am running into some strange file permission errors that I am having a bit of trouble debugging. I'm catching a `Poco::FileException: File access error` [here](https://github.com/brannondorsey/kibio/blob/master/src/Project.cpp#L366) when renaming the `.kibio` file from `kibioDebug.app/Resources/data/templates/TemplateProject/TemplateProject.kibio` to `/Users/bdorse/Documents/Kibio/PROJECT_NAME/PROJECT_NAME.kibio`.

The default permission of `~/Documents/Kibio/PROJECT_NAME/TemplateProject.kibio` after a failed rename is `-rw-------` (fairly conservative permissions, I know) even if I add a `chmod` command to the build script that relaxes those permissions I still receive the error. Any ideas? Also shouldn't an OF app be run as the logged in user anyway?

**Comment by brannondorsey** [comment]
I'm going to try and dig into this today. @bakercp, any immediate thoughts?

**Comment by bakercp** [comment]
You digging in on all the issues or this one in particular?

**Comment by brannondorsey** [comment]
This one in particular. All soon :smile:

**Comment by bakercp** [comment]
Hm ... not sure on this one.  Would need to see code.  It could be an order of operations thing...

**Comment by brannondorsey** [comment]
I linked to code above (but I think that it got out of sync). Here is a link with the line on an actual commit link: https://github.com/brannondorsey/kibio/blob/8b10292dd0c81f434f680ece59806638d9b7fe6f/src/Project.cpp#L373

**Comment by brannondorsey** [comment]
This was a logic error.
